title: 'Rais Helmy | Self Taught Dev'
default_lang: en
author:
  name: 'Rais Helmy bin Sapiullah'
  email: raishelmy97@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'rais helmy made this metadata'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
